HomemadeKitchen/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CasualShop.BLL;
using CasualShop.BLL.DtoModels;
using CasualShop.DAL.Repository;
using CasualShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace CasualShop.Controllers
{
    public class BasketController : Controller
    {
        private DataManager _dataManager;
        private ServicesManager _servicesManager;

        public BasketController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _servicesManager = new ServicesManager(dataManager);
        }
        public IActionResult Index()
        {
            var model = new OrderInfoDto();
            return View(model);
        }
            
        public IActionResult Delete(int basketId)
        {
            _servicesManager.Baskets.DeleteBasketById(basketId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AddToBasket(string userId, int DishesId)
        {
            BasketEditDto _editModel = _servicesManager.Baskets.CreateBasketEditDto();

            _editModel.CurrentUser = userId;
            _editModel.DishesId = DishesId;
            _editModel.Count = 1;
            _editModel.isProcessed = false;
            _servicesManager.Baskets.SaveBasketEditDtoToDb(_editModel);

            return RedirectToAction("Index");
        }        

        [HttpPost]
        public IActionResult Index(string basketCurrentUserId, OrderInfoDto orderInfoDto)
        {
            var _basketModel = _servicesManager.Baskets.GetBasketsList().Where(b => b.CurrentUser == basketCurrentUserId && b.isProcessed == false);
           
                EmailService emailService = new EmailService();

                string emailText = "<div>Firstname: " + orderInfoDto.FirstName + "</div><div>Lastname: " + orderInfoDto.LastName + "</div><div>Phone: " + orderInfoDto.PhoneNum +
                    "</div><div>Email: " + orderInfoDto.Email + "</div><div>";
                int totalPrice = 0;
                foreach (var item in _basketModel)
                {
                    if (item.CurrentUser == basketCurrentUserId && item.isProcessed == false)
                    {
                        var DishesModel = _servicesManager.Dishes.GetDishesModelById(item.DishesId);
                        emailText = emailText + "<div>Dishes name: " + DishesModel.Name + " Price:" + DishesModel.Price + " (UAH)</div>";
                        totalPrice += DishesModel.Price;
                        item.isProcessed = true;
                    }
                    _servicesManager.Baskets.UpdateBasketsDtoToDb(item);
                }
                emailText += "<div style=\"font-weight:bold\">Total price: " + totalPrice.ToString() + "</div></div>";
                emailService.SendEmail(orderInfoDto.Email, "HomemadeKitchen Order",
                    emailText);
                return RedirectToAction("Index", "Shop");            
        }
    }
}

HomemadeKitchen/Views/Basket/AddBasket.cshtml
@{
    ViewData["Title"] = "AddBasket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ДОДАНО ДО КОРЗИНИ</h1>

HomemadeKitchen/Views/Basket/Index.cshtml
@model CasualShop.BLL.DtoModels.OrderInfoDto

@using Microsoft.AspNetCore.Identity
@using CasualShop.Areas.Identity.Data
@using CasualShop.BLL

@inject ServicesManager ServiceManager
@inject SignInManager<CasualShopUser> SignInManager
@inject UserManager<CasualShopUser> UserManager

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .imgfit {
        width: 50px;
        height: 50px;
        object-fit: cover;
    }
</style>

<h1>Basket</h1>
@if (@SignInManager.IsSignedIn(User))
{
    <div class="container">
        <div class="row">
            <table class="table table-bordered table-dark">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Фото</th>
                        <th scope="col">Назва</th>
                        <th scope="col">Ціна</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ServiceManager.Baskets.GetBasketsList())
                    {
                        if (@UserManager.GetUserId(User) == item.CurrentUser && item.isProcessed == false)
                        {
                            <tr>
                                <th scope="row"></th>
                                <th>
                                    @if (ServiceManager.Dishes.GetDishesModelById(item.DishesId).Image == null)
                                    {
                                        <img class="imgfit" src="https://investfuture.ru/images/no_img.jpeg" />
                                    }
                                    else
                                    {
                                        <img class="imgfit"
                                             src="@("~/Image/" + ServiceManager.Dishes.GetDishesModelById(item.DishesId).Image.ImageName)"
                                             asp-append-version="true" />
                                    }
                                </th>
                                <th>
                                    @ServiceManager.Dishes.GetDishesModelById(item.DishesId).Name
                                </th>
                                <th>
                                    @ServiceManager.Dishes.GetDishesModelById(item.DishesId).Price
                                </th>
                                <th>
                                    <button type="button" class="bg-danger"
                                            onclick="location.href='@Url.Action("Delete","Basket",
                                       new { basketId = item.Id})'">
                                        X
                                    </button>

                                </th>
                            </tr>

                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center">
            <h3>Оформлення замовлення</h3>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col">

                <form asp-action="Index" asp-controller="Basket">
                    <div>
                        <div class="validation text-danger" asp-validation-summary="All"></div>
                        <div>
                            <input type="hidden" name="basketCurrentUserId" value="@UserManager.GetUserId(User)" />
                        </div>
                        <div>
                            <div>
                                <label>Ім'я</label>
                            </div>
                            <div>
                                <input type="text" asp-for="FirstName" class="bg-dark rounded" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div>
                            <div>
                                <label>Прізвище</label>
                            </div>
                            <div>
                                <input type="text" asp-for="LastName" class="bg-dark rounded" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                        <div>
                            <div>
                                <label>Номер телефону</label>
                            </div>
                            <div>
                                <input asp-for="PhoneNum" class="bg-dark rounded" />
                                <span asp-validation-for="PhoneNum" class="text-danger"></span>
                            </div>
                        </div>
                        <div>
                            <div>
                                <label>Email</label>
                            </div>
                            <div>
                                <input asp-for="Email" class="bg-dark rounded" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div>
                            <input type="submit" class="btn btn-dark mt-2" value="Зробити замовлення" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>

        @*<button onclick="location.href='@Url.Action("Index","Basket",new {
                                       basketCurrentUserId = UserManager.GetUserId(User),
                                   firstName = "Andrew",
                                   lastName = "Fedorenko",
                                   phoneNum = "123234324",
                                   email = "asdasdasdasd"})'">
                Make order
            </button>*@
    </div>
}
@section scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

HomemadeKitchen/Views/Basket/MakeOrder.cshtml
@{
    ViewData["Title"] = "MakeOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Замовлення прийнято, Менеджер звяжеться з вами</h1>